# Generated by Django 3.2.3 on 2021-06-04 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0005_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='tweet_user', through='tweet.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
