# Generated by Django 3.2.3 on 2021-06-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_remove_like_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweet.tweet'),
        ),
    ]
